### ISSUE TITLE
Security implications of storing OAuth client ID in config.json?

### ISSUE THREAD

**Issue by gpoole** [dorelljames/sanity-plugin-netlify-deploy-status-badge#5]
Hi there, thanks for the great plugin!

I'm wondering about whether there are any security implications to storing the client ID in config.json, since I believe this info is accessible to anyone including unauthenticated users via the js source. I know that it's not totally secret info, but I have seen some people saying it's something better kept private, [for example on ouath.com](https://www.oauth.com/oauth2-servers/client-registration/client-id-secret/) they say:

> Even though it’s public, it’s best that it isn’t guessable by third parties

I wonder if it's worth using something like [sanity-studio-secrets](https://github.com/sanity-io/sanity-studio-secrets) to store the client ID in the data set instead?

I also see that while it isn't documented, the `personalAccessToken` option is supported in the config and I would have thought that's a security risk since that is secret.

**Comment by dorelljames** [comment]
Thanks for the kind remarks!

I've had great ideas when I started working on this plugin but the primary reason why it didn't push through is because of this very concern you're asking me right now. To be honest, and I agree that it's better to keep the OAuth Client Id as a secret and not publicly accessible, say for example it being readable if your studio repo is set to `public`. But even then if not and we're going to use `sanity-studio-secrets` as per your suggestion, you can actually be able to read the value of it if your dataset is to `public` given the right endpoint and api parameters via GROQ to query such value. 

At the time when I created this, I didn't have much knowledge so why I opted with using the  config json file. Knut also suggested the same thing to use `sanity-studio-secrets` but since we're not really specifically storing tokens, and only once you grant the plugin access to your account should it work, figures it's not much of a security risk but that has to say that's just as far as I know. I'd be happy to make changes should I learn more about the implications of how it is right now. Also, I'd be happy to accept contributions to improve the current behavior. 

As for `personalAccessToken`, I never really pushed through implementing it! And I don't think I'll ever will for the reasons that if I'm not mistaken and as I explained earlier, in order to keep that token fully secure,  you have to make sure both your git repo and Sanity dataset is set to private. Thinking about the odds it'll not be followed and tokens possibly leaked (which means full access to anyone's Netlify account), I don't think it's worth it. Better be safe than sorry!
